# Generated by Django 6.0.6 on 2026-06-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status_keanggotaan', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.IntegerField()),
                ('kategori', models.CharField(max_length=100)),
                ('stok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField()),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Terlambat', 'Terlambat')], default='Dipinjam', max_length=15)),
                ('denda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='perpus.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='perpus.buku')),
            ],
        ),
    ]
