# Generated by Django 6.0.6 on 2026-06-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='status_keanggotaan',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='peminjaman',
            old_name='tanggal_kembali',
            new_name='jatuh_tempo',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='email',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='no_telp',
        ),
        migrations.AddField(
            model_name='anggota',
            name='kelas',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anggota',
            name='nis',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='keperluan',
            field=models.CharField(default='Bacaan pribadi', max_length=255),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='keterangan_keperluan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='petugas',
            field=models.CharField(default='Budi Siregar', max_length=100),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='denda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateField(),
        ),
    ]
