# Generated by Django 6.0.6 on 2026-06-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anggota',
            old_name='status_keanggotaan',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='email',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='no_telp',
        ),
        migrations.AddField(
            model_name='anggota',
            name='kelas',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anggota',
            name='nis',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
