# Generated by Django 6.0.6 on 2026-06-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_rename_status_keanggotaan_anggota_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjaman',
            old_name='tanggal_kembali',
            new_name='jatuh_tempo',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='keperluan',
            field=models.CharField(default='Bacaan pribadi', max_length=255),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='keterangan_keperluan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='petugas',
            field=models.CharField(default='Budi Siregar', max_length=100),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='denda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateField(),
        ),
    ]
